### ISSUE TITLE
点击下载之后闪退

### ISSUE THREAD

**Issue by zhiyixu** [Esword618/MoocDownload#1]
mooc 平台

**Comment by Esword618** [comment]
发一下你的config.yaml与课程链接

**Comment by zhiyixu** [comment]
课程链接如下： https://www.icourse163.org/course/JNU-1001929011?tid=1468237458
config.yaml 没有这个文件，我用的是release 里边的安装版本

**Comment by Esword618** [comment]
关闭的课程不可以下载
